## Практическое задание №6

1. Решите линейную систему:


In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2, 3], [4, 0, 6], [7 ,8, 9]])
B = np.array([12, 2, 1])
np.linalg.solve(A, B)

array([-9.2       ,  0.9       ,  6.46666667])

In [3]:
A1 = np.linalg.inv(A)
print(A1)
print("det =", np.linalg.det(A))
np.dot(A1, B)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
det = 59.999999999999986


array([-9.2       ,  0.9       ,  6.46666667])

Найдите псевдорешение

In [4]:
A = np.array([[1, 2, -1], [3, -4, 0], [8 ,-5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

C:\Users\Dmitry\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))

In [5]:
np.dot(A, [ 1.13919353, -0.90498444, -0.9009803 ])

array([ 0.23020495,  7.03751835, 11.83650984,  6.78328856, 15.21805317])

Сколько решений имеет линейная систем

In [6]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]


(2, 3)

Ранг расширенной матрицы больше ранга исходной матрицы, следовательно решений нет

In [7]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 6.5, 1]])
C = np.concatenate((A,B.T), axis=1)
print (C)
np.linalg.matrix_rank(A, 0.0001), np.linalg.matrix_rank(C, 0.0001)

[[ 1.   2.   3.  12. ]
 [ 4.   5.   6.   6.5]
 [ 7.   8.   9.   1. ]]


(2, 2)

Вычислите LU-разложение матрицы:

In [9]:
import numpy as np 
import matplotlib.pyplot as plt
import scipy 
import scipy.linalg  

In [24]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [27]:
B = np.array([1,2,3])
np.linalg.solve(A, B)

array([ 1.01388889,  0.03472222, -0.02777778])

5. Найдите нормальное псевдорешение недоопределенной системы:
x + 2y – z = 1
8x – 5y + 2z = 12
Для этого определите функцию Q(x,y,z), равную норме решения, и найдите ее минимум. 


In [12]:
def Q(x, y, z):
    return (x**2 + y**2 + z**2)

In [13]:
A = np.array([[1, 2, -1], [8, 5, 2]])
B = np.array([1, 12])
np.linalg.lstsq(A, B)

C:\Users\Dmitry\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  This is separate from the ipykernel package so we can avoid doing imports until


(array([1.15562914, 0.27152318, 0.6986755 ]),
 array([], dtype=float64),
 2,
 array([9.79026138, 1.77504425]))

6. Найдите одно из псевдорешений вырожденной системы:

Попробуйте также отыскать и нормальное псевдорешение.


In [20]:
A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print(A)
print(Q)
print(R)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [21]:
R1 = R[:2, :2]

In [17]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.54871729e-15])

In [22]:
X1 = np.linalg.solve(R1, B1)
X1


array([1.50000000e+00, 9.45096256e-15])

In [23]:
X = np.append(X1, 0)
print (X)
np.linalg.norm(X)

[1.50000000e+00 9.45096256e-15 0.00000000e+00]


1.4999999999999893